AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a DynamoDB table for Bicycle Licences'

Parameters:
  TableName:
    Type: String
    Default: BicycleLicence
    Description: Name of the DynamoDB table

Resources:
  BicycleLicenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY

Outputs:
  TableName:
    Description: Name of the created DynamoDB table
    Value: !Ref BicycleLicenceTable
  TableArn:
    Description: ARN of the created DynamoDB table
    Value: !GetAtt BicycleLicenceTable.Arn
